version: 0.2
phases:    
    install:
        runtime-versions:
            nodejs: 10
        commands:            
            - 'touch .npmignore'            
            - 'npm install -g gatsby'    
    pre_build:        
        commands:            
            - 'npm install'    
    build:        
        commands:            
            - 'npm run build'
    post_build:        
        commands:
            - 'mkdir blog'
            - 'mv public/* blog/'
            - 'mv blog/ public/'
            - 'npm run deploy'
        
cache:
    paths:
        - '.cache/*'
        - 'node_modules/*'
        - 'public/*'
